#!/usr/bin/env php
<?php
/*
 * @Author: 7123
 * @Date: 2025-10-18 19:20:55
 * @LastEditors: 7123
 * @LastEditTime: 2025-12-08 04:24:37
 */
// CLI 入口文件

// 启动并获取 DI 容器
// 注意：config/bootstrap.php 返回的是一个数组 [container, whoops]，我们只需要 container
list($container, $whoops_unused) = require __DIR__ . '/config/bootstrap.php';

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Helper\DescriptorHelper;
use Luminode\Core\Console\Descriptor\TextDescriptor;
use Luminode\Core\Console\Commands\MakeControllerCommand;
use Luminode\Core\Console\Commands\MakeModelCommand;
use Luminode\Core\Console\Commands\RouteListCommand;
use Luminode\Core\Console\Commands\MakeViewCommand;
use Luminode\Core\Console\Commands\ServeCommand;
use Luminode\Core\Console\Commands\DashboardCommand;
use Luminode\Core\Console\Commands\DoctorCommand;
use Luminode\Core\Console\Commands\MakeMiddlewareCommand;
use Luminode\Core\Console\Commands\LogClearCommand;
use Luminode\Core\Console\Commands\MakeRouteCommand;

// 创建命令行应用实例
$application = new Application('Open Luminode CLI', '2.1.0');

// --- 汉化默认命令描述 ---
try {
    $defaultCommands = [
        'list' => '列出可用命令',
        'help' => '显示命令帮助信息',
        'completion' => '生成 Shell 自动补全脚本'
    ];
    foreach ($defaultCommands as $name => $desc) {
        if ($application->has($name)) {
            $command = $application->get($name);
            $command->setDescription($desc);
        }
    }
} catch (\Throwable $e) {
    // 忽略错误
}

// --- 手动注册所有命令 ---
// 使用 DI 容器来创建命令实例，以便自动注入依赖
$application->add($container->get(MakeControllerCommand::class));
$application->add($container->get(MakeModelCommand::class));
$application->add($container->get(RouteListCommand::class));
$application->add($container->get(MakeViewCommand::class));
$application->add($container->get(ServeCommand::class));
$application->add($container->get(DashboardCommand::class));
$application->add($container->get(DoctorCommand::class));
$application->add($container->get(MakeMiddlewareCommand::class));
$application->add($container->get(LogClearCommand::class));
$application->add($container->get(MakeRouteCommand::class));

// 运行应用
$application->run();